apiVersion: kuma.io/v1alpha1
kind: MeshLoadBalancingStrategy
metadata:
  name: disable-zone-preference
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: MeshService
      name: demo-app_kuma-demo_svc_5000
    default:
      localityAwareness:
        disabled: true
      loadBalancer:
        type: RoundRobin